defmodule Aoc.Day08Test do
  use ExUnit.Case

  import Elixir.Aoc.Day08

  def test_input() do
    """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """
  end

  test "part1" do
    input = test_input()
    result = part1(input)

    assert result == 14
  end

  test "part2" do
    input = test_input()
    result = part2(input)

    assert result == 34
  end
end
